from pst.models.environment import Environment
from pst.models.stage import Stage


class CertStage(Stage):
    def __init__(self):
        super().__init__(
            name="cert",
            environments=[
                Environment(
                    name="fbg-cert-1",
                    aws_account_name="sportsbook-cert",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1-debezium-1",
                    aws_account_name="sportsbook-cert",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1-data-1",
                    aws_account_name="sportsbook-cert",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1c",
                    aws_account_name="sportsbook-cert-child-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1tn",
                    aws_account_name="sportsbook-cert-child-tn-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1va",
                    aws_account_name="sportsbook-cert-child-va-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1oh",
                    aws_account_name="sportsbook-cert-child-oh-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1ma",
                    aws_account_name="sportsbook-cert-child-ma-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1md",
                    aws_account_name="sportsbook-cert-child-md-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1mi",
                    aws_account_name="sportsbook-cert-child-mi-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1co",
                    aws_account_name="sportsbook-cert-child-co-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1pa",
                    aws_account_name="sportsbook-cert-child-pa-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1nj",
                    aws_account_name="sportsbook-cert-child-nj-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1ks",
                    aws_account_name="sportsbook-cert-child-ks-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1ky",
                    aws_account_name="sportsbook-cert-child-ky-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1wv",
                    aws_account_name="sportsbook-cert-child-wv-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1ct",
                    aws_account_name="sportsbook-cert-child-ct-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1nc",
                    aws_account_name="sportsbook-cert-child-nc-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1ia",
                    aws_account_name="sportsbook-cert-child-ia-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1ny",
                    aws_account_name="sportsbook-cert-child-ny-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1vt",
                    aws_account_name="sportsbook-cert-child-vt-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-cert-1il",
                    aws_account_name="sportsbook-cert-child-il-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1in",
                    aws_account_name="sportsbook-cert-child-in-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1az",
                    aws_account_name="sportsbook-cert-child-az-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1wy",
                    aws_account_name="sportsbook-cert-child-wy-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1la",
                    aws_account_name="sportsbook-cert-child-la-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-cert-1dc",
                    aws_account_name="sportsbook-cert-child-dc-1",
                    aws_region="us-east-1",
                ),
            ],
        )
