from pst.models.environment import Environment
from pst.models.stage import Stage


class ProdStage(Stage):
    def __init__(self):
        super().__init__(
            name="prod",
            environments=[
                Environment(
                    name="fbg-prod-1",
                    aws_account_name="sportsbook-prod",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1-debezium-1",
                    aws_account_name="sportsbook-prod",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1-data-1",
                    aws_account_name="sportsbook-prod",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1az",
                    aws_account_name="sportsbook-prod-child-az-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1tn",
                    aws_account_name="sportsbook-prod-child-tn-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1va",
                    aws_account_name="sportsbook-prod-child-va-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1oh",
                    aws_account_name="sportsbook-prod-child-oh-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1ma",
                    aws_account_name="sportsbook-prod-child-ma-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1md",
                    aws_account_name="sportsbook-prod-child-md-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1co",
                    aws_account_name="sportsbook-prod-child-co-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1ky",
                    aws_account_name="sportsbook-prod-child-ky-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1wv",
                    aws_account_name="sportsbook-prod-child-wv-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1ct",
                    aws_account_name="sportsbook-prod-child-ct-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1nc",
                    aws_account_name="sportsbook-prod-child-nc-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1nj",
                    aws_account_name="sportsbook-prod-child-nj-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1mi",
                    aws_account_name="sportsbook-prod-child-mi-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1pa",
                    aws_account_name="sportsbook-prod-child-pa-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1il",
                    aws_account_name="sportsbook-prod-child-il-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1vt",
                    aws_account_name="sportsbook-prod-child-vt-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1in",
                    aws_account_name="sportsbook-prod-child-in-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1ny",
                    aws_account_name="sportsbook-prod-child-ny-1",
                    aws_region="us-east-1",
                ),
                Environment(
                    name="fbg-prod-1ia",
                    aws_account_name="sportsbook-prod-child-ia-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1ks",
                    aws_account_name="sportsbook-prod-child-ks-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1wy",
                    aws_account_name="sportsbook-prod-child-wy-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1la",
                    aws_account_name="sportsbook-prod-child-la-1",
                    aws_region="us-east-2",
                ),
                Environment(
                    name="fbg-prod-1dc",
                    aws_account_name="sportsbook-prod-child-dc-1",
                    aws_region="us-east-1",
                ),
            ],
        )
